Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113306
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113466
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113607
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
Internal Server Error: /
Traceback (most recent call last):
  File ".\authentication\views\home_views.py", line 335, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\home_views.py", line 352, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 167, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 169, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2025-04-28 12:35:07,189 login_views 23920 24304 Error sending WebSocket notification: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:45,525 login_views 23920 26852 Error sending WebSocket notification: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:52,159 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:52,163 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:57,203 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:57,209 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,215 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,222 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,256 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,260 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:04,981 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:10,035 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:10,040 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,055 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,064 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,080 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,086 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:18,271 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:18,276 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:23,336 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:23,342 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,338 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,343 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,516 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,523 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:49,540 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:49,544 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:54,610 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:54,617 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,624 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,631 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,660 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,664 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:45:41,469 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:48,538 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:53,566 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:55,601 consumers 5428 17960 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:50,166 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:52,204 consumers 5428 17960 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:57,218 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:57,281 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:50:17,116 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:50:24,188 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:18,214 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:20,244 consumers 13572 11972 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:25,349 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-05-06 10:25:28,891 login_views 30512 9884 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:27:41,182 login_views 3352 29508 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:28:14,970 login_views 3352 19616 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:03,907 login_views 3352 26000 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:19,679 login_views 3352 19424 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:48,269 consumers 3352 27112 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:50,306 consumers 3352 27112 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:42,737 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:49,817 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:55,886 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:57,924 consumers 21336 13948 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:44:02,964 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:01:43,582 login_views 19676 29096 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:20,004 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:45,848 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:56,926 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:04,009 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:04,589 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:06,062 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:40:03,516 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
