Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113306
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113466
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113607
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
Internal Server Error: /
Traceback (most recent call last):
  File ".\authentication\views\home_views.py", line 335, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\home_views.py", line 352, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 167, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 169, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2025-04-28 12:35:07,189 login_views 23920 24304 Error sending WebSocket notification: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:45,525 login_views 23920 26852 Error sending WebSocket notification: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:52,159 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:52,163 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:57,203 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:35:57,209 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,215 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,222 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,256 consumers 23920 28928 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:36:02,260 consumers 23920 28928 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:04,981 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:10,035 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:10,040 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,055 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,064 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,080 consumers 31704 22404 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:41:15,086 consumers 31704 22404 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:18,271 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:18,276 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:23,336 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:23,342 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,338 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,343 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,516 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:42:28,523 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:49,540 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:49,544 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:54,610 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:54,617 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,624 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,631 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,660 consumers 21908 5968 Error in WebSocket connect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:43:59,664 consumers 21908 5968 Error in WebSocket disconnect: Client sent AUTH, but no password is set
ERROR 2025-04-28 12:45:41,469 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:48,538 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:53,566 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:45:55,601 consumers 5428 17960 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:50,166 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:52,204 consumers 5428 17960 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:57,218 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:49:57,281 consumers 5428 17960 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:50:17,116 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:50:24,188 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:18,214 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:20,244 consumers 13572 11972 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-04-28 12:51:25,349 consumers 13572 11972 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. 10061.
ERROR 2025-05-06 10:25:28,891 login_views 30512 9884 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:27:41,182 login_views 3352 29508 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:28:14,970 login_views 3352 19616 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:03,907 login_views 3352 26000 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:19,679 login_views 3352 19424 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:48,269 consumers 3352 27112 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:32:50,306 consumers 3352 27112 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:42,737 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:49,817 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:55,886 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:43:57,924 consumers 21336 13948 Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 10:44:02,964 consumers 21336 13948 Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:01:43,582 login_views 19676 29096 Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:20,004 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:45,848 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:03:56,926 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:04,009 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:04,589 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:04:06,062 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 12:40:03,516 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:35:11,672 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:35:23,193 log Internal Server Error: /
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\pymongo\collection.py", line 3478, in __next__
    raise TypeError("'Collection' object is not iterable")
TypeError: 'Collection' object is not iterable
ERROR 2025-05-06 15:37:05,485 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:07,543 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:12,560 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:12,575 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:14,617 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:25,618 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:37:48,410 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 15:46:43,829 employee_views Error processing account 680f23f3b7fc59289c6a4167: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,831 employee_views Error processing account 680f23f3b7fc59289c6a4168: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,833 employee_views Error processing account 680f240db7fc59289c6a416d: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,834 employee_views Error processing account 680f3835bc409388a9aff38c: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,836 employee_views Error processing account 680f3e3e9a7034b37c1d7c2a: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,838 employee_views Error processing account 680f3e3e9a7034b37c1d7c2b: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,839 employee_views Error processing account 680f3e3e9a7034b37c1d7c2c: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,840 employee_views Error processing account 680f3e3e9a7034b37c1d7c2d: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,842 employee_views Error processing account 680f3e3e9a7034b37c1d7c2e: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,844 employee_views Error processing account 680f3e3e9a7034b37c1d7c2f: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,845 employee_views Error processing account 680f3e3e9a7034b37c1d7c30: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,847 employee_views Error processing account 680f3e3e9a7034b37c1d7c31: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,849 employee_views Error processing account 6816e167e75efe2bbaba5288: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,850 employee_views Error processing account 6816e1b7e75efe2bbaba5289: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,852 employee_views Error processing account 6816e1b7e75efe2bbaba528a: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,853 employee_views Error processing account 68174a4e2056bbaab1ad09b8: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,854 employee_views Error processing account 68174cca9350013cd1289895: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,856 employee_views Error processing account 68174dcb3d836b5924df0602: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,858 employee_views Error processing account 68174ddac4ae57cac9dc0f93: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,859 employee_views Error processing account 68174eac3fa7075b351ad0f7: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,861 employee_views Error processing account 6819a76215c516351f122508: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,862 employee_views Error processing account 6819a76215c516351f122509: name 'timezone' is not defined
ERROR 2025-05-06 15:46:43,864 employee_views Error processing account 6819a76215c516351f12250a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,545 employee_views Error processing account 680f23f3b7fc59289c6a4167: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,547 employee_views Error processing account 680f23f3b7fc59289c6a4168: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,548 employee_views Error processing account 680f240db7fc59289c6a416d: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,550 employee_views Error processing account 680f3835bc409388a9aff38c: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,551 employee_views Error processing account 680f3e3e9a7034b37c1d7c2a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,553 employee_views Error processing account 680f3e3e9a7034b37c1d7c2b: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,554 employee_views Error processing account 680f3e3e9a7034b37c1d7c2c: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,556 employee_views Error processing account 680f3e3e9a7034b37c1d7c2d: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,557 employee_views Error processing account 680f3e3e9a7034b37c1d7c2e: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,559 employee_views Error processing account 680f3e3e9a7034b37c1d7c2f: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,560 employee_views Error processing account 680f3e3e9a7034b37c1d7c30: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,562 employee_views Error processing account 680f3e3e9a7034b37c1d7c31: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,563 employee_views Error processing account 6816e167e75efe2bbaba5288: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,565 employee_views Error processing account 6816e1b7e75efe2bbaba5289: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,566 employee_views Error processing account 6816e1b7e75efe2bbaba528a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,568 employee_views Error processing account 68174a4e2056bbaab1ad09b8: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,570 employee_views Error processing account 68174cca9350013cd1289895: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,571 employee_views Error processing account 68174dcb3d836b5924df0602: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,573 employee_views Error processing account 68174ddac4ae57cac9dc0f93: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,574 employee_views Error processing account 68174eac3fa7075b351ad0f7: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,575 employee_views Error processing account 6819a76215c516351f122508: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,576 employee_views Error processing account 6819a76215c516351f122509: name 'timezone' is not defined
ERROR 2025-05-06 15:48:00,577 employee_views Error processing account 6819a76215c516351f12250a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,737 employee_views Error processing account 680f23f3b7fc59289c6a4167: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,739 employee_views Error processing account 680f23f3b7fc59289c6a4168: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,740 employee_views Error processing account 680f240db7fc59289c6a416d: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,742 employee_views Error processing account 680f3835bc409388a9aff38c: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,743 employee_views Error processing account 680f3e3e9a7034b37c1d7c2a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,744 employee_views Error processing account 680f3e3e9a7034b37c1d7c2b: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,745 employee_views Error processing account 680f3e3e9a7034b37c1d7c2c: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,747 employee_views Error processing account 680f3e3e9a7034b37c1d7c2d: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,748 employee_views Error processing account 680f3e3e9a7034b37c1d7c2e: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,749 employee_views Error processing account 680f3e3e9a7034b37c1d7c2f: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,750 employee_views Error processing account 680f3e3e9a7034b37c1d7c30: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,751 employee_views Error processing account 680f3e3e9a7034b37c1d7c31: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,752 employee_views Error processing account 6816e167e75efe2bbaba5288: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,753 employee_views Error processing account 6816e1b7e75efe2bbaba5289: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,755 employee_views Error processing account 6816e1b7e75efe2bbaba528a: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,756 employee_views Error processing account 68174a4e2056bbaab1ad09b8: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,757 employee_views Error processing account 68174cca9350013cd1289895: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,758 employee_views Error processing account 68174dcb3d836b5924df0602: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,759 employee_views Error processing account 68174ddac4ae57cac9dc0f93: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,761 employee_views Error processing account 68174eac3fa7075b351ad0f7: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,762 employee_views Error processing account 6819a76215c516351f122508: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,764 employee_views Error processing account 6819a76215c516351f122509: name 'timezone' is not defined
ERROR 2025-05-06 15:48:47,765 employee_views Error processing account 6819a76215c516351f12250a: name 'timezone' is not defined
ERROR 2025-05-06 15:49:58,964 employee_views Error in employee_verified_view: authentication/employee_verified.html
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 437, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
ERROR 2025-05-06 15:49:59,130 log Internal Server Error: /verified/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 437, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 449, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
ERROR 2025-05-06 15:51:42,831 employee_views Error in employee_verified_view: verified.html
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 437, in employee_verified_view
    return render(request, 'verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: verified.html
ERROR 2025-05-06 15:51:42,962 log Internal Server Error: /verified/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 437, in employee_verified_view
    return render(request, 'verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 449, in employee_verified_view
    return render(request, 'verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: verified.html
ERROR 2025-05-06 15:57:42,427 verified_views Error in employee_verified_view: authentication/employee_verified.html
Traceback (most recent call last):
  File ".\authentication\views\verified_views.py", line 100, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
ERROR 2025-05-06 15:57:42,543 log Internal Server Error: /verified/
Traceback (most recent call last):
  File ".\authentication\views\verified_views.py", line 100, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\verified_views.py", line 112, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
ERROR 2025-05-06 16:00:44,363 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:07,959 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:21,708 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:23,745 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:28,792 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:28,808 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:30,843 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:01:30,858 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:04:36,257 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:05:02,537 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:09:47,859 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:10:24,662 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:10:43,868 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:11:16,545 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-06 16:14:32,673 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 09:58:36,220 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 11:57:11,710 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 11:57:31,057 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 12:05:50,764 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:46:30,336 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:47:25,913 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:48:00,093 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:48:16,456 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:48:38,420 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:49:03,426 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:49:34,032 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:54:55,209 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:55:19,374 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:55:31,776 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:56:47,529 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:06,528 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:13,609 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:14,288 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:37,735 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:56,989 consumers Error in WebSocket connect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:57:59,035 consumers Error in WebSocket disconnect: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 13:58:18,115 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:04:55,265 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:05:11,673 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:27:51,660 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:36:52,932 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:53:53,541 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 14:54:20,570 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 15:56:42,564 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 16:45:18,887 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-07 16:45:36,296 login_views Error sending WebSocket notification: Error 10061 connecting to 127.0.0.1:6379. Connect call failed ('127.0.0.1', 6379).
ERROR 2025-05-08 11:52:37,928 login_views Error sending WebSocket notification: Error 22 connecting to 127.0.0.1:6379. 22.
ERROR 2025-05-08 11:52:50,089 home_views Error in home_view: Cannot use MongoClient after close
ERROR 2025-05-08 11:52:50,205 basehttp "GET / HTTP/1.1" 500 193655
ERROR 2025-05-08 11:53:12,555 home_views Error in home_view: Cannot use MongoClient after close
ERROR 2025-05-08 11:53:12,656 basehttp "GET / HTTP/1.1" 500 193882
ERROR 2025-05-08 11:53:14,861 home_views Error in home_view: Cannot use MongoClient after close
ERROR 2025-05-08 11:53:14,963 basehttp "GET / HTTP/1.1" 500 194019
ERROR 2025-05-08 11:53:26,592 home_views Error in home_view: Cannot use MongoClient after close
ERROR 2025-05-08 11:53:26,717 basehttp "GET / HTTP/1.1" 500 194019
