Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113306
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113466
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113607
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
Internal Server Error: /
Traceback (most recent call last):
  File ".\authentication\views\home_views.py", line 335, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\home_views.py", line 352, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 167, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 169, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 72
Internal Server Error: /available-emails/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 795, in email_info_view
    return render(request, 'authentication/employee_email_info.html', {
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'employee_work' not found. 'employee_work' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 801, in email_info_view
    return redirect('employee_work')
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'employee_work' not found. 'employee_work' is not a valid view function or pattern name.
"GET /available-emails/ HTTP/1.1" 500 144014
Internal Server Error: /available-emails/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 795, in email_info_view
    return render(request, 'authentication/employee_email_info.html', {
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'employee_work' not found. 'employee_work' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 801, in email_info_view
    return redirect('employee_work')
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'employee_work' not found. 'employee_work' is not a valid view function or pattern name.
"GET /available-emails/ HTTP/1.1" 500 144304
Internal Server Error: /available-emails/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view authentication.views.employee_views.email_info_view didn't return an HttpResponse object. It returned None instead.
"GET /available-emails/ HTTP/1.1" 500 69807
Internal Server Error: /available-emails/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view authentication.views.employee_views.email_info_view didn't return an HttpResponse object. It returned None instead.
"GET /available-emails/ HTTP/1.1" 500 69808
Internal Server Error: /available-emails/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view authentication.views.employee_views.email_info_view didn't return an HttpResponse object. It returned None instead.
"GET /available-emails/ HTTP/1.1" 500 69808
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\login_views.py", line 42, in login_view
    if users_collection:
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\pymongo\synchronous\collection.py", line 311, in __bool__
    raise NotImplementedError(
NotImplementedError: Collection objects do not implement truth value testing or bool(). Please compare with None instead: collection is not None
"GET /login/ HTTP/1.1" 500 73629
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 65
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 65
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 66
Internal Server Error: /api/available-emails/
"GET /api/available-emails/ HTTP/1.1" 500 66
Internal Server Error: /create-mail/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 306, in create_email_view
    return render(request, 'authentication/create_email.html')
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/create_email.html
"GET /create-mail/ HTTP/1.1" 500 87699
Internal Server Error: /create-mail/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 305, in create_email_view
    return render(request, 'authentication/create_email.html')
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/create_email.html
"GET /create-mail/ HTTP/1.1" 500 87699
Internal Server Error: /create-mail/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\employee_views.py", line 305, in create_email_view
    return render(request, 'authentication/create_email.html')
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/create_email.html
"GET /create-mail/ HTTP/1.1" 500 87699
Internal Server Error: /create-mail/
"GET /create-mail/ HTTP/1.1" 500 63
Internal Server Error: /create-mail/
"GET /create-mail/ HTTP/1.1" 500 63
Internal Server Error: /api/create-textnow/
"POST /api/create-textnow/ HTTP/1.1" 500 66
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 40
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 40
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 40
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 40
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73395
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73395
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73395
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73395
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73227
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73532
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73532
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\login_views.py", line 72, in login_view
    if client:
UnboundLocalError: local variable 'client' referenced before assignment
"POST /login/ HTTP/1.1" 500 69327
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\login_views.py", line 72, in login_view
    if client:
UnboundLocalError: local variable 'client' referenced before assignment
"POST /login/ HTTP/1.1" 500 69327
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\webDjango1704\authentication\views\login_views.py", line 72, in login_view
    if client:
UnboundLocalError: local variable 'client' referenced before assignment
"POST /login/ HTTP/1.1" 500 69331
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73822
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73043
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73042
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73369
Internal Server Error: /create-password/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\employee_views.py", line 262, in create_password_view
    if client:
UnboundLocalError: local variable 'client' referenced before assignment
"POST /create-password/ HTTP/1.1" 500 74848
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73051
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73051
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73052
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73051
Internal Server Error: /work/
"GET /work/ HTTP/1.1" 500 141
Internal Server Error: /work/
"GET /work/ HTTP/1.1" 500 141
Internal Server Error: /work/
"GET /work/ HTTP/1.1" 500 141
Internal Server Error: /work/
"GET /work/ HTTP/1.1" 500 141
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 141
Internal Server Error: /verified/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\employee_views.py", line 295, in employee_verified_view
    if client:
UnboundLocalError: local variable 'client' referenced before assignment
"GET /verified/ HTTP/1.1" 500 73141
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73043
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73043
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73361
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73372
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73042
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 72912
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 93
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 93
Internal Server Error: /available-emails/
"GET /available-emails/ HTTP/1.1" 500 79
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 74727
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73237
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 73354
Internal Server Error: /manager/admin
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 82, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /manager/admin HTTP/1.1" 500 139224
Internal Server Error: /manager-admin-sale
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 82, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /manager-admin-sale HTTP/1.1" 500 139299
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 82, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /manager-admin-sale/ HTTP/1.1" 500 139314
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 82, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /manager-admin-sale/ HTTP/1.1" 500 139314
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 88, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 95, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /manager-admin-sale/ HTTP/1.1" 500 203107
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '!=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 136, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '!==' from '!=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '!=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 144, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '!==' from '!=='
"GET /manager-admin-sale/?date_type=range&single_date=&status_tn=&created_by=nhanvien_user&search= HTTP/1.1" 500 316309
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 135, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 143, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'
"GET /manager-admin-sale/?date_type=single&start_date=2025-04-27&end_date=2025-04-27&status_tn=&created_by=&search= HTTP/1.1" 500 348890
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 137, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 145, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'
"GET /manager-admin-sale/?date_type=single&start_date=2025-04-27&end_date=2025-04-27&status_tn=&created_by=&search= HTTP/1.1" 500 345500
Internal Server Error: /manager-admin-sale/
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 137, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 766, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 782, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\functional.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\utils\text.py", line 388, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'employee._id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\manger_admin_sale_views.py", line 145, in manager_textnow_view
    return render(request, 'authentication/manager_textnow_admin_sale.html', context)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 648, in __init__
    var_obj = Variable(var)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 787, in __init__
    raise TemplateSyntaxError("Variables and attributes may "
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'employee._id'
"GET /manager-admin-sale/?date_type=single&start_date=2025-04-27&end_date=2025-04-27&status_tn=&created_by=&search= HTTP/1.1" 500 345500
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MT GAMING\Desktop\git thong\WebDjango\authentication\views\home_views.py", line 128, in home_view
    users_collection, client = get_collection_handle('users')
TypeError: 'Collection' object is not iterable
"GET / HTTP/1.1" 500 74204
